<?php
//classes do frame work
require("tupi.configuracao.php");
require("tupi.biblioteca.php");
require("tupi.persistencia.php");
require("tupi.php");
require("tupi.template.php");
require("tupi.mensagem.php");
require("tupi.css2inline.php");
//require("tupi.cielo.php");

//classes de negocio
require("modelo.Uf.php");
require("modelo.Cidade.php");
require("modelo.Usuario.php");
require("modelo.Perfil.php");
require("modelo.Acesso.php");
require("modelo.Menu.php");
require("modelo.LogAcesso.php");
require("modelo.LogGrupo.php");
require("modelo.Cliente.php");
require("modelo.EstadoCivil.php");
require("modelo.Grupo.php");
require("modelo.Moeda.php");
require("modelo.StatusGrupo.php");
require("modelo.PautaReuniao.php");
require("modelo.Participante.php");
require("modelo.StatusParticipante.php");
require("modelo.Voo.php");
require("modelo.CompanhiaAerea.php");
require("modelo.Quarto.php");
require("modelo.Distribuicao.php");
require("modelo.Banco.php");
require("modelo.BandeiraCartao.php");
require("modelo.Pagamento.php");
require("modelo.TipoPagamento.php");
require("modelo.TipoTransferencia.php");
require("modelo.Abatimento.php");
require("modelo.Cheque.php");
require("modelo.Carne.php");
require("modelo.Credito.php");
require("modelo.FinalidadePagamento.php");
require("modelo.TipoConta.php");
require("modelo.Conta.php");
require("modelo.ContaRealizado.php");
require("modelo.StatusCheque.php");
require("modelo.LogParticipante.php");
require("modelo.LogUsuario.php");
require("modelo.Agendamento.php");
require("modelo.Ticket.php");
?>