<?php
//classes do frame work
include("tupi.configuracao.php");
include("tupi.biblioteca.php");
include("tupi.persistencia.php");
include("tupi.php");
include("tupi.template.php");
include("tupi.mensagem.php");
include("tupi.css2inline.php");
//include("tupi.cielo.php");

//classes de negocio
include("modelo.Uf.php");
include("modelo.Cidade.php");
include("modelo.Usuario.php");
include("modelo.Perfil.php");
include("modelo.Acesso.php");
include("modelo.Menu.php");
include("modelo.LogAcesso.php");
include("modelo.LogGrupo.php");
include("modelo.Cliente.php");
include("modelo.EstadoCivil.php");
include("modelo.Grupo.php");
include("modelo.Moeda.php");
include("modelo.StatusGrupo.php");
include("modelo.PautaReuniao.php");
include("modelo.Participante.php");
include("modelo.StatusParticipante.php");
include("modelo.Voo.php");
include("modelo.CompanhiaAerea.php");
include("modelo.Quarto.php");
include("modelo.Distribuicao.php");
include("modelo.Banco.php");
include("modelo.BandeiraCartao.php");
include("modelo.Pagamento.php");
include("modelo.TipoPagamento.php");
include("modelo.TipoTransferencia.php");
include("modelo.Abatimento.php");
include("modelo.Cheque.php");
include("modelo.Carne.php");
include("modelo.Credito.php");
include("modelo.FinalidadePagamento.php");
include("modelo.TipoConta.php");
include("modelo.Conta.php");
include("modelo.ContaRealizado.php");
include("modelo.StatusCheque.php");
include("modelo.LogParticipante.php");
include("modelo.LogUsuario.php");
include("modelo.Agendamento.php");
include("modelo.Ticket.php");
?>